import { boolean, integer, pgTable, real, text } from 'drizzle-orm/pg-core'
import { elementTypes, teams } from '../../db/schema.js'

export const elements = pgTable('elements', {
  id: integer('id').primaryKey(),
  can_transact: boolean('can_transact'),
  can_select: boolean('can_select'),
  chance_of_playing_next_round: integer('chance_of_playing_next_round'),
  chance_of_playing_this_round: integer('chance_of_playing_this_round'),
  code: integer('code').notNull(),
  cost_change_event: integer('cost_change_event'),
  cost_change_event_fall: integer('cost_change_event_fall'),
  cost_change_start: integer('cost_change_start'),
  cost_change_start_fall: integer('cost_change_start_fall'),
  dreamteam_count: integer('dreamteam_count'),
  element_type: integer('element_type').references(() => elementTypes.id),
  ep_next: real('ep_next'),
  ep_this: real('ep_this'),
  event_points: integer('event_points'),
  first_name: text('first_name').notNull(),
  form: real('form'),
  in_dreamteam: boolean('in_dreamteam'),
  news: text('news'),
  news_added: text('news_added'),
  now_cost: real('now_cost').notNull(),
  photo: text('photo'),
  points_per_game: real('points_per_game'),
  removed: boolean('removed'),
  second_name: text('second_name').notNull(),
  selected_by_percent: real('selected_by_percent'),
  special: boolean('special'),
  squad_number: integer('squad_number'),
  status: text('status'),
  team: integer('team').references(() => teams.id),
  team_code: integer('team_code'),
  total_points: integer('total_points'),
  transfers_in: integer('transfers_in'),
  transfers_in_event: integer('transfers_in_event'),
  transfers_out: integer('transfers_out'),
  transfers_out_event: integer('transfers_out_event'),
  value_form: real('value_form'),
  value_season: real('value_season'),
  web_name: text('web_name').notNull(),
  region: integer('region'),
  team_join_date: text('team_join_date'),
  birth_date: text('birth_date'),
  has_temporary_code: boolean('has_temporary_code'),
  opta_code: text('opta_code'),
  minutes: integer('minutes'),
  goals_scored: integer('goals_scored'),
  assists: integer('assists'),
  clean_sheets: integer('clean_sheets'),
  goals_conceded: integer('goals_conceded'),
  own_goals: integer('own_goals'),
  penalties_saved: integer('penalties_saved'),
  penalties_missed: integer('penalties_missed'),
  yellow_cards: integer('yellow_cards'),
  red_cards: integer('red_cards'),
  saves: integer('saves'),
  bonus: integer('bonus'),
  bps: integer('bps'),
  influence: real('influence'),
  creativity: real('creativity'),
  threat: real('threat'),
  ict_index: real('ict_index'),
  clearances_blocks_interceptions: integer('clearances_blocks_interceptions'),
  recoveries: integer('recoveries'),
  tackles: integer('tackles'),
  defensive_contribution: integer('defensive_contribution'),
  starts: integer('starts'),
  expected_goals: real('expected_goals'),
  expected_assists: real('expected_assists'),
  expected_goal_involvements: real('expected_goal_involvements'),
  expected_goals_conceded: real('expected_goals_conceded'),
})
