import { boolean, integer, pgTable, text } from 'drizzle-orm/pg-core'

export const teams = pgTable('teams', {
  id: integer('id').primaryKey(),
  code: integer('code'),
  draw: integer('draw').default(0),
  form: text('form'),
  loss: integer('loss').default(0),
  name: text('name').notNull(),
  played: integer('played').default(0),
  points: integer('points').default(0),
  position: integer('position'),
  short_name: text('short_name'),
  strength: integer('strength'),
  team_division: integer('team_division'),
  unavailable: boolean('unavailable').default(false),
  win: integer('win').default(0),
  strength_overall_home: integer('strength_overall_home'),
  strength_overall_away: integer('strength_overall_away'),
  strength_attack_home: integer('strength_attack_home'),
  strength_attack_away: integer('strength_attack_away'),
  strength_defence_home: integer('strength_defence_home'),
  strength_defence_away: integer('strength_defence_away'),
  pulse_id: integer('pulse_id'),
})
